// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Break.Module.Core.DAL;

#nullable disable

namespace Break.Module.Core.DAL.Migrations
{
    [DbContext(typeof(DbInstace))]
    [Migration("20250202161812_Break")]
    partial class Break
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Modules.Break.Module.Core.Entity.BrakeTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("BrakeEndTime")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("BrakeStartTime")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("busyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("busyId")
                        .IsUnique();

                    b.ToTable("BrakeTimes");
                });

            modelBuilder.Entity("Modules.Break.Module.Core.Entity.DateTimeWorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrakeTimeMapId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BrakeTimeMapId");

                    b.ToTable("DateTimeWorkSchedules");
                });

            modelBuilder.Entity("Modules.Break.Module.Core.Entity.busyChecker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("busy")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("BusyCheckers");
                });

            modelBuilder.Entity("Modules.Break.Module.Core.Entity.BrakeTime", b =>
                {
                    b.HasOne("Modules.Break.Module.Core.Entity.busyChecker", "busyChecker")
                        .WithOne()
                        .HasForeignKey("Modules.Break.Module.Core.Entity.BrakeTime", "busyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("busyChecker");
                });

            modelBuilder.Entity("Modules.Break.Module.Core.Entity.DateTimeWorkSchedule", b =>
                {
                    b.HasOne("Modules.Break.Module.Core.Entity.BrakeTime", "BrakeTimeMap")
                        .WithMany()
                        .HasForeignKey("BrakeTimeMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrakeTimeMap");
                });
#pragma warning restore 612, 618
        }
    }
}
