// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeInTimeOut.Module.Core.DAL;

#nullable disable

namespace TimeInTimeOut.Module.Core.DAL.Migrations
{
    [DbContext(typeof(DbInstaceTimeInOut))]
    [Migration("20250204091522_IcomingAndgoingUser")]
    partial class IcomingAndgoingUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimeInTimeOut.Module.Core.Domain.Entity.ComingAndgoing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OfflineTime")
                        .HasColumnType("JSON");

                    b.Property<string>("OnlineTime")
                        .HasColumnType("JSON");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComingAndgoings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
